# Generated by Django 5.2.7 on 2025-10-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreColor', models.CharField(max_length=50)),
                ('codigoHex', models.CharField(max_length=7)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PRO_Color',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEntidad', models.CharField(max_length=100)),
                ('documentoIdentidad', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GEN_Entidad',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PRO_Marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreModelo', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PRO_Modelo',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('acceso', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GEN_Permiso',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GEN_Rol',
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PRO_Talla',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('imagen', models.URLField()),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('idColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.color')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.marca')),
                ('idModelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.modelo')),
                ('idTalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.talla')),
            ],
            options={
                'db_table': 'GEN_Producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('idEntidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.entidad')),
                ('idPermiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.permiso')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProyecto.rol')),
            ],
            options={
                'db_table': 'GEN_Usuario',
            },
        ),
    ]
